global TableResult
global diameter
global Qs
global length
global Qp
global Qtotal



fprintf(['\n','This report has been generated by SinglePileCapacityCalculator v1.0 on ' date])

fprintf(['\n','The soil properties and pile dimensions used in calculations are provided below.','\n'])

disp(TableResult)
fprintf(['\n','Pile Diameter(m): ' num2str(diameter)])
fprintf(['\n','Pile Length(m): ' num2str(length)])
fprintf(['\n','Skin Friction(kN): ' num2str(Qs)])
fprintf(['\n','Tip Resistance(kN): ' num2str(Qp)])
fprintf(['\n','Ultimate Capacity(kN): ' num2str(Qtotal)])



